---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kube-agent
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: codefresh-kube-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
      app.kubernetes.io/component: codefresh-kube-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
        app.kubernetes.io/component: codefresh-kube-agent
    spec:
      containers:
      - image: {{ .Values.imageCodefresh }}
        imagePullPolicy: Always
        name: kube-agent
        env:
        - name: API_HOST
          value: {{ .Values.codefreshApiEndpoint | default "https://g.codefresh.io" | quote }}
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: codefreshApiKey
        - name: CLUSTER_NAME
          value: gke-{{ .Release.Name }}
        - name: KUBE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: kubeEndpoint
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
