---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-codefresh-dind-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: codefresh-dind-role
rules:
- apiGroups: [""]
  resources: ["services","pods","configmaps","secrets"]
  verbs: ["get", "list","watch", "create","update", "patch","delete"]
