---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: codefresh-secret
type: Opaque
data:
  codefreshApiKey: {{ .Values.codefreshApiKey | b64enc | quote }}
  kubeEndpoint: {{ .Values.kubeEndpoint| b64enc | quote }}
