application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  imageCodefresh:
    type: string
    default: $REGISTRY/codefresh-marketplace:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageCodefreshRepo
            after: imageCodefreshTag
  codefreshApiKey:
    type: string
    title: Codefresh API Key
    description: This is a Codefresh API token which you create in Codefresh Account Settings.
  serviceAccount:
    type: string
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for Codefresh
      to work properly with your cluster.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- reportingSecret
- imageCodefresh
- codefreshApiKey
- serviceAccount
