application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageCodefresh:
    type: string
    default: $REGISTRY/codefresh-marketplace:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageCodefreshRepo
            after: imageCodefreshTag
  codefreshApiKey:
    type: string
  codefreshApiEndpoint:
    type: string
    default: "https://g.codefresh.io"
  kubeEndpoint:
    type: string
required:
- name
- namespace
- imageCodefresh
- codefreshApiKey
- kubeEndpoint
