application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageCodefresh:
    type: string
    default: $REGISTRY/kube-agent:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageCodefreshRepo
            after: imageCodefreshTag
  imageInit:
    type: string
    default: $REGISTRY/init:$TAG
    x-google-marketplace:
      type: IMAGE
  imageMysql:
    type: string
    default: $REGISTRY/mysql:$TAG
    x-google-marketplace:
      type: IMAGE
  imageUbbagent:
    type: string
    default: $REGISTRY/ubbagent:$TAG
    x-google-marketplace:
      type: IMAGE
  dbPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  customString:
    title: Blog title
    description: Codefresh requires a blog title for setup. This can be changed later.
    type: string
    default: 'My blog'
    maxLength: 128
    pattern: '[A-Za-z0-9 -]+'
  customInteger:
    title: Server replicas
    type: integer
    default: 1
    minimum: 1
    maximum: 128
  customBoolean:
    title: A custom boolean parameter.
    type: boolean
    default: false
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  codefreshApiKey:
    type: string
required:
- name
- namespace
- codefreshApiKey
- imageCodefresh
- imageInit
- imageMysql
- imageUbbagent
- dbPassword
- customString
- customInteger
- customBoolean
- reportingSecret
