application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  imageCodefresh:
    type: string
    default: $REGISTRY/codefresh-marketplace:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageCodefreshRepo
            after: imageCodefreshTag
  codefreshApiKey:
    type: string
    title: Codefresh API Key
    description: This is a Codefresh API token which you create in Codefresh Account Settings.
  kubeEndpoint:
    type: string
    title: Kubernetes Endpoint
    description: This is the "Endpoint" of the cluster (IP address). Copy this from the cluster's details in Google Cloud console.
required:
- name
- namespace
- reportingSecret
- imageCodefresh
- codefreshApiKey
- kubeEndpoint
